version: "3.8"

services:
  capture:
    build: ./capture
    volumes:
      - ./capture:/app
    command: python capture.py
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

  flowgen:
    build: ./flowgen
    volumes:
      - ./capture/pcaps:/app/pcaps
      - ./flowgen/flows:/app/output
    depends_on:
      - capture
    networks:
      - spooky-net
    command: ["python3", "flowgen.py", "/app/pcaps/example.pcap", "/app/output"]

  model:
    build: ./model
    volumes:
      - ./model:/app
      - ./flowgen/flows:/app/flows
    command: uvicorn predictor_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - spooky-net

  honeypot:
    build: ./honeypot
    volumes:
      - ./honeypot:/app
    command: python honeypot.py
    networks:
      - spooky-net

  gui:
    build: ./gui
    volumes:
      - ./gui:/app
    command: python gui.py
    networks:
      - spooky-net
    ports:
      - "5000:5000"

  spookyserver:
    build: ./server
    container_name: spookyserver
    environment:
      - HP_USER=spooky
      - HP_PASS=5P00F
    networks:
      spooky-macvlan:
        ipv4_address: 192.168.10.13
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  spooky-net:
    driver: bridge

  spooky-macvlan:
    driver: macvlan
    driver_opts:
      parent: intspooky
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.11
