version: "3.8"

services:
  capture:
    build: ./capture
    volumes:
      - ./capture:/app
    command: python capture.py
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

  flowgen:
    build: ./flowgen
    volumes:
      - ./capture/pcaps:/app/pcaps   # Carpeta compartida de PCAPs
      - ./flowgen/flows:/app/output  # Carpeta donde se guardan los CSV
    depends_on:
      - capture
    networks:
      - spooky-net
    # Ejemplo de ejecución (puedes cambiar el archivo pcap):
    command: ["python3", "flowgen.py", "/app/pcaps/example.pcap", "/app/output"]

  model:
    build: ./model
    volumes:
      - ./model:/app
      - ./flowgen/flows:/app/flows   # Lee los CSV generados por flowgen
    command: uvicorn predictor_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - spooky-net

  honeypot:
    build: ./honeypot
    volumes:
      - ./honeypot:/app
    command: python honeypot.py
    networks:
      - spooky-net

  gui:
    build: ./gui
    volumes:
      - ./gui:/app
    command: python gui.py
    networks:
      - spooky-net
    ports:
      - "5000:5000"

networks:
  spooky-net:
    driver: bridge
